import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CodeSpace0.1v",
  description: "Generated by me",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full h-full p-4 bg-[#050505]`}
      >
        {children}
      </body>
    </html>
  );
}
